### PR TITLE
Change ci,cd and sourceControl fields to Ids Issue 287

### PR DESCRIPTION
**Pull request by sandyasheri-gft**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Read, understand and follow the **[contribution guidelines](https://www.tranquilitybase.io/contribution-guidelines/)**
- [ ] Tested UI/API integration with current master:
  - [ ] Login
  - [ ] "Create New Solution"
  - [ ] "Create New Application"
  - [ ] "Create New WAN VPN"
  - [ ] Dev user is able to request access to a "Locked" Activator
  - [ ] Admin user is able to "Grant Access", "Lock", "Deprecate" and "Undeprecate" an Activator

## PR Type
What kind of change does this PR introduce?

Please check the one that applies to this PR.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] TranquilityBase application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing stack below.

### CODE REVIEW

**Comment by sandyasheri-gft** [comment]
Please use below image to test these changes

**tb-houston-service:review**

gcr.io/tranquility-base-images/tb-houston-service@sha256:099e188da3a2fdb1b438fe37cd34a58bd59f3f95ed8b6d002dd54d6244a531d8

**Comment by Salles-FA** [comment]
Created Docker image:
- gcr.io/tranquility-base-images/tb-houston-service:review

**Comment by karwootang-gft** [comment]
Example solution deployment json sent to the DaC from the logs:
```
houston-service_1  | DEBUG:tb_houston_service.solution_deployment:send_solution_deployment_to_the_dac::solution_deployment: {
houston-service_1  |     "lastUpdated": "2020-07-06 17:41:20",
houston-service_1  |     "sourceControlId": 2,
houston-service_1  |     "name": "General Ledger",
houston-service_1  |     "teamId": 1,
houston-service_1  |     "deploymentFolderId": "MOCKFOLDERID3",
houston-service_1  |     "isActive": true,
houston-service_1  |     "businessUnit": "Modern Apps",
houston-service_1  |     "team": {
houston-service_1  |         "lastUpdated": "2020-03-01 12:34:56",
houston-service_1  |         "businessUnitId": 1,
houston-service_1  |         "name": "Developers",
houston-service_1  |         "isActive": true,
houston-service_1  |         "businessUnit": {
houston-service_1  |             "description": "Modern Apps",
houston-service_1  |             "name": "Modern Apps",
houston-service_1  |             "id": 1,
houston-service_1  |             "isActive": true
houston-service_1  |         },
houston-service_1  |         "description": "All Developers",
houston-service_1  |         "teamMembers": [
houston-service_1  |             {
houston-service_1  |                 "role": "<tb_houston_service.models.Role object at 0x7fa9559a9710>",
houston-service_1  |                 "id": 2,
houston-service_1  |                 "user": {
houston-service_1  |                     "isAdmin": false,
houston-service_1  |                     "lastUpdated": "2020-03-01 12:34:56",
houston-service_1  |                     "lastName": "Snow",
houston-service_1  |                     "email": "dev@your.company",
houston-service_1  |                     "isActive": true,
houston-service_1  |                     "showWelcome": true,
houston-service_1  |                     "firstName": "Jon",
houston-service_1  |                     "id": 1
houston-service_1  |                 }
houston-service_1  |             }
houston-service_1  |         ],
houston-service_1  |         "id": 1
houston-service_1  |     },
houston-service_1  |     "environments": [
houston-service_1  |         "Development"
houston-service_1  |     ],
houston-service_1  |     "ciId": 2,
houston-service_1  |     "isFavourite": false,
houston-service_1  |     "description": "A general ledger (GL) is a set of numbered accounts a business uses to keep track of its financial transactions and to prepare financial reports.",
houston-service_1  |     "cdId": 4,
houston-service_1  |     "sourceControl": {
houston-service_1  |         "value": "Cloud native",
houston-service_1  |         "id": 2
houston-service_1  |     },
houston-service_1  |     "costCentre": "ldf-343-sds-232",
houston-service_1  |     "ci": {
houston-service_1  |         "value": "Cloud native",
houston-service_1  |         "id": 2
houston-service_1  |     },
houston-service_1  |     "id": 9,
houston-service_1  |     "cd": {
houston-service_1  |         "value": "Team City",
houston-service_1  |         "id": 4
houston-service_1  |     }
houston-service_1  | }
```

**Comment by karwootang-gft** [comment]
Example application/activator deployment:

```
houston-service_1  | DEBUG:tb_houston_service.application_deployment:send_application_deployment_to_the_dac::application_deployment: {
houston-service_1  |     "name": "test",
houston-service_1  |     "id": 5,
houston-service_1  |     "description": "test",
houston-service_1  |     "activatorGitUrl": "",
houston-service_1  |     "mandatoryVariables": [],
houston-service_1  |     "optionalVariables": [],
houston-service_1  |     "deploymentEnvironment": "development-1",
houston-service_1  |     "deploymentProjectId": "development-1-h08aez-ksjs726s",
houston-service_1  |     "workspaceProjectId": "workspace-h08aez-ksjs726s",
houston-service_1  |     "lastUpdated": "2020-07-06 18:01:31",
houston-service_1  |     "solutionId": 9
houston-service_1  | }
```

**Pull request merged**
