### PR TITLE
#398 Add the ability to create Sandbox Solutions

### LINKED ISSUE #398: [Feature] Add the ability to create Sandbox Solutions
https://github.com/tranquilitybase-io/tb-eagle-console/issues/321

### PR DESCRIPTION
**Pull request by Salles-FA**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Read, understand and follow the **[contribution guidelines](https://www.tranquilitybase.io/contribution-guidelines/)**
- [x] Tested UI/API integration with current master:
  - [x] Login
  - [x] "Create New Solution"
  - [x] "Create New Application"
  - [x] "Create New WAN VPN"
  - [x] Dev user is able to request access to a "Locked" Activator
  - [x] Admin user is able to "Grant Access", "Lock", "Deprecate" and "Undeprecate" an Activator

## PR Type
What kind of change does this PR introduce?

Please check the one that applies to this PR.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] TranquilityBase application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: closes #398 

## What is the new behavior?
This PR adds the ability to create a sandbox solution

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing stack below.

### CODE REVIEW

**Comment by Salles-FA** [comment]
Tested with Swagger Creating, Updating, Listing, Filtering etc.

Used this JSON to POST `/api/solution/`:
```json
{
  "id": 0,
  "name": "Sandbox",
  "description": "Try it out",
  "businessUnitId": 1,
  "teamId": 2,
  "costCentre": "12345",
  "isSandbox": true
}
```

**Comment by Salles-FA** [comment]
Created a new 'review' Docker image:
- `gcr.io/tranquility-base-images/tb-houston-service:review`

**Comment by Salles-FA** [comment]
image

**Review by sunderhill-gft — APPROVED** [review]
Looks good

**Pull request merged**
