### PR TITLE
PR for Issue 379

### PR DESCRIPTION
**Pull request by karwootang-gft**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Read, understand and follow the **[contribution guidelines](https://www.tranquilitybase.io/contribution-guidelines/)**
- [ ] Tested UI/API integration with current master:
  - [ ] Login
  - [ ] "Create New Solution"
  - [ ] "Create New Application"
  - [ ] "Create New WAN VPN"
  - [ ] Dev user is able to request access to a "Locked" Activator
  - [ ] Admin user is able to "Grant Access", "Lock", "Deprecate" and "Undeprecate" an Activator

## PR Type
What kind of change does this PR introduce?

Please check the one that applies to this PR.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] TranquilityBase application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing stack below.

### CODE REVIEW

**Comment by karwootang-gft** [comment]
Tested activator PUT operation with this JSON payload:

{
"accessRequestedBy": null,
"accessRequestedById": null,
"activator": null,
"activatorMetadata": {
"activatorLink": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
"category": "Infrastructure",
"description": "A helloworld example of an activator.",
"id": 13,
"lastUpdated": "2020-09-15 13:57:59",
"name": "Tranquility Base GFT Base",
"platforms": [
{
"id": 1,
"value": "GCP"
}
],
"type": {
"id": 3,
"value": "Tier 3"
},
"typeId": 3,
"variables": [
{
"activatorMetadataId": 13,
"id": 16,
"isOptional": false,
"name": "standard_subnetwork",
"type": "string",
"value": "new value",
"defaultValue": "DEFAULT"
},
{
"activatorMetadataId": 13,
"id": 17,
"isOptional": false,
"name": "zone",
"type": "tb_zone",
"value": "new value",
"defaultValue": "DEFAULT"
},
{
"activatorMetadataId": 13,
"id": 18,
"isOptional": false,
"name": "host_project_id",
"type": "string",
"value": "new value",
"defaultValue": "DEFAULT"
},
{
"activatorMetadataId": 13,
"id": 19,
"isOptional": false,
"name": "region",
"type": "tb_region",
"value": "new value",
"defaultValue": "DEFAULT"
},
{
"activatorMetadataId": 13,
"id": 20,
"isOptional": true,
"name": "vms_size",
"type": "tb_vms_size",
"value": "new value",
"defaultValue": "DEFAULT"
}
]
},
"apiManagement": null,
"available": null,
"billing": null,
"businessUnit": null,
"businessUnitId": null,
"cd": [3],
"ci": [3],
"envs": [1],
"gitRepoUrl": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
"hosting": null,
"id": 13,
"isActive": true,
"isFavourite": false,
"lastUpdated": "2020-09-15 13:57:59",
"name": "Tranquility Base GFT Base",
"regions": null,
"sensitivity": null,
"serverCapacity": null,
"source": null,
"sourceControl": null,
"sourceControlId": null,
"status": "Draft",
"technologyOwner": null,
"technologyOwnerEmail": null,
"userCapacity": null
}

**Comment by Salles-FA** [comment]
Created new 'review' docker image:

 - gcr.io/tranquility-base-images/tb-houston-service:

**Comment by Salles-FA** [comment]
This JSON is been sent to `/api/activator/{oid}` PUT at step 2. Only the Activator Variables are to be updated.

The issue is: 
 -  The API is returning status 200 but isn't updating the variables.

```json
{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": null,
  "activatorMetadata": {
    "activatorLink": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
    "category": "Infrastructure",
    "description": "A helloworld example of an activator.",
    "id": 12,
    "lastUpdated": "2020-09-23 13:34:29",
    "name": "Tranquility Base GFT Base",
    "platforms": [
      {
        "id": 1,
        "value": "GCP"
      }
    ],
    "type": {
      "id": 3,
      "value": "Tier 3"
    },
    "typeId": 3,
    "variables": [
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 1,
        "isOptional": false,
        "name": "standard_subnetwork",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 2,
        "isOptional": false,
        "name": "zone",
        "type": "tb_zone",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 3,
        "isOptional": false,
        "name": "host_project_id",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 4,
        "isOptional": false,
        "name": "region",
        "type": "tb_region",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 5,
        "isOptional": true,
        "name": "vms_size",
        "type": "tb_vms_size",
        "value": ""
      }
    ]
  },
  "apiManagement": null,
  "available": null,
  "billing": null,
  "businessUnit": null,
  "businessUnitId": null,
  "cd": [],
  "ci": [],
  "envs": [],
  "gitRepoUrl": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
  "hosting": null,
  "id": 12,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-09-23 13:34:29",
  "name": "Tranquility Base GFT Base",
  "regions": null,
  "sensitivity": null,
  "serverCapacity": null,
  "source": null,
  "sourceControl": null,
  "sourceControlId": null,
  "status": "Draft",
  "technologyOwner": null,
  "technologyOwnerEmail": null,
  "userCapacity": null
}
```

image

**Review by Salles-FA — CHANGES_REQUESTED** [review]
The API is returning status 200 but isn't updating variables.

**Comment by karwootang-gft** [comment]
In the logs I found these errors:

ERROR:tb_houston_service.activator_extension:ci details in activator are missing, the transaction will be rolled back for this activator!
ERROR:tb_houston_service.activator_extension:cd details in activator are missing, the transaction will be rolled back for this activator!
ERROR:tb_houston_service.activator_extension:env details in activator are missing, the transaction will be rolled back for this activator!

Returning != 200 is existing behavior.
Let's discuss.

**Comment by Salles-FA** [comment]
Hi @karwootang-gft ,

As discussed ci, cd and env lists are going to be filled in by the user during step 3. For step 2 only default Values for the activator variables are going to be filled in. 

Thx.

**Comment by karwootang-gft** [comment]
As discussed with Fabio remove the cd, cd and env validation.

Below json was posted and go the corresponding response below that:

{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": null,
  "activatorMetadata": {
    "activatorLink": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
    "category": "Infrastructure",
    "description": "A helloworld example of an activator.",
    "id": 12,
    "lastUpdated": "2020-09-28 14:39:47",
    "name": "Tranquility Base GFT Base",
    "platforms": [
      {
        "id": 1,
        "value": "GCP"
      }
    ],
    "type": {
      "id": 3,
      "value": "Tier 3"
    },
    "typeId": 3,
    "variables": [
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 11,
        "isOptional": false,
        "name": "standard_subnetwork",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 12,
        "isOptional": false,
        "name": "zone",
        "type": "tb_zone",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 13,
        "isOptional": false,
        "name": "host_project_id",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 14,
        "isOptional": false,
        "name": "region",
        "type": "tb_region",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 15,
        "isOptional": true,
        "name": "vms_size",
        "type": "tb_vms_size",
        "value": ""
      }
    ]
  },
  "apiManagement": null,
  "available": null,
  "billing": null,
  "businessUnit": null,
  "businessUnitId": null,
  "cd": [],
  "ci": [],
  "envs": [],
  "gitRepoUrl": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
  "hosting": null,
  "id": 12,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-09-28 14:39:47",
  "name": "Tranquility Base GFT Base",
  "regions": null,
  "sensitivity": null,
  "serverCapacity": null,
  "source": null,
  "sourceControl": null,
  "sourceControlId": null,
  "status": "Draft",
  "technologyOwner": null,
  "technologyOwnerEmail": null,
  "userCapacity": null
}

Response:

{
  "accessRequestedBy": null,
  "accessRequestedById": null,
  "activator": null,
  "activatorMetadata": {
    "activatorLink": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
    "category": "Infrastructure",
    "description": "A helloworld example of an activator.",
    "id": 12,
    "lastUpdated": "2020-09-28 14:40:31",
    "name": "Tranquility Base GFT Base",
    "platforms": [
      {
        "id": 1,
        "value": "GCP"
      }
    ],
    "type": {
      "id": 3,
      "value": "Tier 3"
    },
    "typeId": 3,
    "variables": [
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 11,
        "isOptional": false,
        "name": "standard_subnetwork",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 12,
        "isOptional": false,
        "name": "zone",
        "type": "tb_zone",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 13,
        "isOptional": false,
        "name": "host_project_id",
        "type": "string",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 14,
        "isOptional": false,
        "name": "region",
        "type": "tb_region",
        "value": ""
      },
      {
        "activatorMetadataId": 12,
        "defaultValue": "Test",
        "id": 15,
        "isOptional": true,
        "name": "vms_size",
        "type": "tb_vms_size",
        "value": ""
      }
    ]
  },
  "apiManagement": null,
  "available": null,
  "billing": null,
  "businessUnit": null,
  "businessUnitId": null,
  "cd": [],
  "ci": [],
  "envs": [],
  "gitRepoUrl": "https://github.com/tranquilitybase-io/tb-activator-gft-base",
  "hosting": null,
  "id": 12,
  "isActive": true,
  "isFavourite": false,
  "lastUpdated": "2020-09-28 14:40:31",
  "name": "Tranquility Base GFT Base",
  "regions": null,
  "sensitivity": null,
  "serverCapacity": null,
  "source": null,
  "sourceControl": null,
  "sourceControlId": null,
  "status": "Draft",
  "technologyOwner": null,
  "technologyOwnerEmail": null,
  "userCapacity": null
}

**Comment by Salles-FA** [comment]
Created new 'review' Docker image:
 -  gcr.io/tranquility-base-images/tb-houston-service:review

**Review by Salles-FA — APPROVED** [review]
Tests passed. All clear now

**Pull request merged**
