### PR TITLE
LAN VPC Refactor + Query Parameters + return objects in the POST 

### PR DESCRIPTION
**Pull request by karwootang-gft**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Read, understand and follow the **[contribution guidelines](https://www.tranquilitybase.io/contribution-guidelines/)**
- [ ] Tested UI/API integration with current master:
  - [ ] Login
  - [ ] "Create New Solution"
  - [ ] "Create New Application"
  - [ ] "Create New WAN VPN"
  - [ ] Dev user is able to request access to a "Locked" Activator
  - [ ] Admin user is able to "Grant Access", "Lock", "Deprecate" and "Undeprecate" an Activator

## PR Type
What kind of change does this PR introduce?

Please check the one that applies to this PR.

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] TranquilityBase application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Please describe the current behavior that you are modifying, or link to a relevant issue.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing stack below.

### CODE REVIEW

**Comment by Salles-FA** [comment]
Created docker images:

- gcr.io/tranquility-base-images/tb-houston-service:review
- gcr.io/tranquility-base-images/tb-houston-mysql57:review

**Comment by Salles-FA** [comment]
### 1.  POST `/api/lzmetadataLanVpc/?readActiveOnly=true&bulkDelete=true`

```json
[
  {
    "environments": [1,2],
    "isActive": true,
    "name": "Review VPC"
  }
]
```

**Response OK**:

```json
[
  {
    "environments": [
      {
        "id": 1,
        "isActive": true,
        "name": "Development"
      },
      {
        "id": 2,
        "isActive": true,
        "name": "Production"
      }
    ],
    "id": 5,
    "isActive": true,
    "name": "Review VPC"
  }
]
```

### 2. POST `/api/lzmetadataLanVpc/?readActiveOnly=true&bulkDelete=true`

```json
[
  {
    "environments": [1,3],
    "isActive": true,
    "name": "Review VPC"
  }
]
```

**Response NOT OK**:

```json
[
  {
    "environments": [
      {
        "id": 1,
        "isActive": true,
        "name": "Development"
      },
      {
        "id": 2,
        "isActive": true,
        "name": "Production"
      },
      {
        "id": 3,
        "isActive": true,
        "name": "test-env"
      }
    ],
    "id": 5,
    "isActive": true,
    "name": "Review VPC"
  }
]
```

**Expected behavior**:

```json
[
  {
    "environments": [
      {
        "id": 1,
        "isActive": true,
        "name": "Development"
      },
      {
        "id": 3,
        "isActive": true,
        "name": "test-env"
      }
    ],
    "id": 5,
    "isActive": true,
    "name": "Review VPC"
  }
]
```

**Comment by karwootang-gft** [comment]
> ### 1. POST `/api/lzmetadataLanVpc/?readActiveOnly=true&bulkDelete=true`
> ```json
> [
>   {
>     "environments": [1,2],
>     "isActive": true,
>     "name": "Review VPC"
>   }
> ]
> ```
> 
> **Response OK**:
> 
> ```json
> [
>   {
>     "environments": [
>       {
>         "id": 1,
>         "isActive": true,
>         "name": "Development"
>       },
>       {
>         "id": 2,
>         "isActive": true,
>         "name": "Production"
>       }
>     ],
>     "id": 5,
>     "isActive": true,
>     "name": "Review VPC"
>   }
> ]
> ```
> 
> ### 2. POST `/api/lzmetadataLanVpc/?readActiveOnly=true&bulkDelete=true`
> ```json
> [
>   {
>     "environments": [1,3],
>     "isActive": true,
>     "name": "Review VPC"
>   }
> ]
> ```
> 
> **Response NOT OK**:
> 
> ```json
> [
>   {
>     "environments": [
>       {
>         "id": 1,
>         "isActive": true,
>         "name": "Development"
>       },
>       {
>         "id": 2,
>         "isActive": true,
>         "name": "Production"
>       },
>       {
>         "id": 3,
>         "isActive": true,
>         "name": "test-env"
>       }
>     ],
>     "id": 5,
>     "isActive": true,
>     "name": "Review VPC"
>   }
> ]
> ```
> 
> **Expected behavior**:
> 
> ```json
> [
>   {
>     "environments": [
>       {
>         "id": 1,
>         "isActive": true,
>         "name": "Development"
>       },
>       {
>         "id": 3,
>         "isActive": true,
>         "name": "test-env"
>       }
>     ],
>     "id": 5,
>     "isActive": true,
>     "name": "Review VPC"
>   }
> ]
> ```





This is what I'm seeing in my version. 

```
[
  {
    "environments": [
      {
        "id": 1,
        "isActive": true,
        "name": "Development"
      },
      {
        "id": 3,
        "isActive": true,
        "name": "test-env"
      }
    ],
    "id": 5,
    "isActive": true,
    "name": "Review VPC"
  }
]
```

**Comment by Salles-FA** [comment]
Created docker images:

gcr.io/tranquility-base-images/tb-houston-service:review
gcr.io/tranquility-base-images/tb-houston-mysql57:review

**Comment by Salles-FA** [comment]
Created docker images:

- gcr.io/tranquility-base-images/tb-houston-service:review
- gcr.io/tranquility-base-images/tb-houston-mysql57:review

**Pull request merged**
